apiVersion: v1
kind: Pod
metadata: 
  name: mypod
spec: 
  containers:
    - name: mycontainer
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts: 
      - name: mypod-storage
        mountPath: /usr/test
  volumes:
  - emptyDir: {}
    name: mypod-storage
   

